# This file was generated by GoReleaser. DO NOT EDIT.
cask "cifail" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "4b86e01b7eaeea2fc2b7835d5d156596d57d852a0012acdb41c4f5286b27783a"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e8434f39847c86d68dbff0b73e5b118b56da4d71dad296f64aa224f8c0b0de3"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f50354a8499bcf8914c022bccfda31195eef3133c40ffb9c818b09c36972b085"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5543ec945ca4baa227d3c696361ca5de55e961a7910fab9e2bcb82e70c37ce1a"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cifail"
  desc "Bounded, high-signal extractor of a GitHub Actions run's failing logs (for agents)"
  homepage "https://github.com/akira-toriyama/cifail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cifail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cifail"]
    end
  end

  # No zap stanza required

end
