# This file was generated by GoReleaser. DO NOT EDIT.
cask "cifail" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c91c8a5399f759bc5a93bed6219f9c69580f4f5b591b37bf5e059d862e3f8363"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fcc409c0669ac8eb27f1e6b81bbd91be5941c20954ec64bfbe7d3176c5857c1"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a003270efe22df53ff5c68606c1701a5f670046bd127128fa54a0e018ae6397"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07546ca8f3786eae9ce1a583aea4103615419c5d46a3b0d84194312cdb1f6a3d"
      url "https://github.com/akira-toriyama/cifail/releases/download/v#{version}/cifail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cifail"
  desc "Bounded, high-signal extractor of a GitHub Actions run's failing logs (for agents)"
  homepage "https://github.com/akira-toriyama/cifail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cifail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cifail"]
    end
  end

  # No zap stanza required

end
