# This file was generated by GoReleaser. DO NOT EDIT.
cask "furrow" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "dbdcffea1d54d1c4e548d11c77dc545e5951f9566ed552faec5e0c2e0c3f39e4"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6da449cf10c2bdcc32940625b7507f04970fd184cd6ea99a693b0b35fff72f24"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca1b13d6e68b3e697bbe0c0df45631590be7de96e1e28af6e19b0616efcede44"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "135acd6eb58fbd09af0b27d78140933899828e0eb0f3c1f42f9e29de0a5426de"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "furrow"
  desc "Repo-local plain-text task tracker (JSON index + per-task markdown bodies)"
  homepage "https://github.com/akira-toriyama/furrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "furrow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/furrow"]
    end
  end

  # No zap stanza required

end
