# This file was generated by GoReleaser. DO NOT EDIT.
cask "furrow" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c676ea624e187505a5f7e1d4447a1267eb2cd379e1c34082bceca7349972e290"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b7300969b4b17d7ba35b85d1a6977761eeb4b3281f318b70b776da28c0817ee"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20686f6399dd1f411417eaaa6e7d567fe08729f74dac3225082b7702615e3f86"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e85437308753f1856f0d4fad561c26e7948fd7881882095061aecada526a0fd3"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "furrow"
  desc "Repo-local plain-text task tracker (JSON index + per-task markdown bodies)"
  homepage "https://github.com/akira-toriyama/furrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "furrow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/furrow"]
    end
  end

  # No zap stanza required

end
