# This file was generated by GoReleaser. DO NOT EDIT.
cask "furrow" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "b6c60b71eef091934a4f894d6c8e40bf833ed2d560c8300fb70bdba1c4940cd7"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61b544dde92ca8d6379bef887555804aee783a0734326c723c346a197c4ddd6a"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0702dd902b8fb1f5901d0a0b9a3bc64c9a8b90295fb01410409edc812f438d6"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df63ffb8651ea69d318b8012670db2a8202bcf5f111537076a9450bc7a1dc7cb"
      url "https://github.com/akira-toriyama/furrow/releases/download/v#{version}/furrow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "furrow"
  desc "Clonable, git-native plain-text task tracker — an alternative to GitHub Projects/Issues"
  homepage "https://github.com/akira-toriyama/furrow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "furrow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/furrow"]
    end
  end

  # No zap stanza required

end
