# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "4d5a707b52355b32a2de1ae28ca8e3793f919ce87ba87fff02359299ccda3054"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac02bd288bef053adcda430c255da24be8cb46367a9d47ba6024e0efe0f3bc8b"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f9cfd061212fa847302805671a52dba0ef7c56196c9af3e5d65e4e9abbfdb2d"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "95f9a4db90656aec11285f1eb7bf62b7afd67c3100212b8708d87ae0f7410f59"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glyph"
  desc "gitmoji-driven commit-lint, semver, and release notes for squash-merge repos"
  homepage "https://github.com/akira-toriyama/glyph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required

end
