# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "3.3.0"

  on_macos do
    on_arm do
      sha256 "5cac7398a9315a3469081c603354b9f4386c28914535c9242d19322c6e20e8cd"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b97f65323a65692ccf1df34f4458b4dc12a9b76c7c17ee320f55d92818ffbcd8"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "673a7ce266b8098fe39fe8db5f36681bed415857ade10a89ed2a4cdce66db0fa"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "55375a5877b0334e86e4de1b3666e5661f2ffd9b78522c7ff6572122fe25e332"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
  end

  name "glyph"
  desc "gitmoji-driven commit-lint, semver, and release notes for squash-merge repos"
  homepage "https://github.com/akira-toriyama/glyph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required
end
