# This file was generated by GoReleaser. DO NOT EDIT.
cask "glyph" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "ff56da6b6dcc717b1f7355d47ee7933dab8093a00c9de3c5b71807181d70de90"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13bf59c0a9f1b75b151582f57372dfafdfe92ca5cc2ea4e6724ed5fe14ca0344"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55463e774902ed201307d5b1932733fd08b1c8741e111e2562b6bbce1a000125"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9cbb868dc898f605b5214b64a9753fd3f31140af377b50a80ed50ce61608acac"
      url "https://github.com/akira-toriyama/glyph/releases/download/v#{version}/glyph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glyph"
  desc "gitmoji-driven commit-lint, semver, and release notes for squash-merge repos"
  homepage "https://github.com/akira-toriyama/glyph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glyph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glyph"]
    end
  end

  # No zap stanza required

end
