# This file was generated by GoReleaser. DO NOT EDIT.
cask "mergeprobe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "74be99e1289395520fea12c9be5a35294e4c4dd08bba5e1bbc32bf8d8b1d9da5"
      url "https://github.com/akira-toriyama/mergeprobe/releases/download/v#{version}/mergeprobe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea3169e72d141b16c2b26d8ca4a2c87b692fdc77187a4e1d20adcdf1f15a2367"
      url "https://github.com/akira-toriyama/mergeprobe/releases/download/v#{version}/mergeprobe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f85346e40ac7b919736da905eb4b71c1cdc3bb1b49c118fb5635a5ed3033f1af"
      url "https://github.com/akira-toriyama/mergeprobe/releases/download/v#{version}/mergeprobe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b050b39e1d1fc33ec39f65675f1f4343bccc6701d10c958b27c3d6da35f4264d"
      url "https://github.com/akira-toriyama/mergeprobe/releases/download/v#{version}/mergeprobe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mergeprobe"
  desc "Probe what a branch or PR conflicts with — where and how badly — without touching the worktree; bounded JSON for AI agents"
  homepage "https://github.com/akira-toriyama/mergeprobe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mergeprobe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mergeprobe"]
    end
  end

  # No zap stanza required

end
