# This file was generated by GoReleaser. DO NOT EDIT.
cask "pare" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8a994c1abf0b76590e06d50d67cafc320b961add77ea522b5c51151e9b25ea05"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "44fb3a3899dd24dde4aa91216595a973aa326dc77babac80198224420ef605e4"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e796aa6503255a64772e302f83991b38b06543d9058c27eedcda9b1620698aae"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5b83c09d4ea26da4579609b121d994112a60e37d8ea161885baa071d38d4205"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pare"
  desc "Context-budget-aware output truncation for AI coding agents — head + error lines + tail within a byte budget"
  homepage "https://github.com/akira-toriyama/pare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pare"]
    end
  end

  # No zap stanza required

end
