# This file was generated by GoReleaser. DO NOT EDIT.
cask "pare" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "46651adfeeda149125a27e0ef4d70c02b9921f466082a494282ef28338b72881"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7da1c5f1663b5e9077282a06dbf38bb11db404e99138d8c559b368a5dde884eb"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91defe3fb18c429c874e0060c430f7c64ca290f6b8ca6f5b3af9cea78f1cc4e9"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1089b55b131ae54e9162b4d66645ecc73697964574ff9b9d1a6354189a6fb08f"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pare"
  desc "Context-budget-aware output truncation for AI coding agents — head + error lines + tail within a byte budget"
  homepage "https://github.com/akira-toriyama/pare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pare"]
    end
  end

  # No zap stanza required

end
