# This file was generated by GoReleaser. DO NOT EDIT.
cask "pare" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c24f8a8b6b6cdbc148c31204e69cb265e31f77962d5ebb5b1c670090849f64e3"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "19182be5ea4a0c7ace8978a9f424b11a57540d299e57e4264de40cec17f6f586"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6e5510e34d405ca46223744c8ad02f82c33a98ba82db52e2b31fd2584d9749c"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "294cfc06a8c385ca827805b874adc722764011399e0734dc255f677a7b8bb173"
      url "https://github.com/akira-toriyama/pare/releases/download/v#{version}/pare_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pare"
  desc "Context-budget-aware output truncation for AI coding agents — head + error lines + tail within a byte budget"
  homepage "https://github.com/akira-toriyama/pare"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pare"]
    end
  end

  # No zap stanza required

end
