# This file was generated by GoReleaser. DO NOT EDIT.
cask "prq" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f986366c1de7a0d4e7ac9f00828b5f982f06376f200d5b0872b7355495a1367f"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67ef2ae698d41915e49a01dbb353e19faa2e972986c4727b9024b37958d17f9b"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a47183a69471fdb07e145ae2e24adaa9477f5ad3e2c5ca680108f25db8ea3c23"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b55c18c4eb857038c97bd8f965e49e0a4e52525b60c34076a80d146b47e485b7"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prq"
  desc "One-call PR state synthesis for AI coding agents — why is this PR blocked?"
  homepage "https://github.com/akira-toriyama/prq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prq"]
    end
  end

  # No zap stanza required

end
