# This file was generated by GoReleaser. DO NOT EDIT.
cask "prq" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "8b86af64125f0c8ded89772be38f07ab3bf87ddce634977c0f85be141bcafd0a"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "922f7c6907cb3ec800f22cf46157994e94438daaaae75940ee84e33bd7c07379"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e978589f7f2b2c3d98666771e26f3a7e6c70b4e7561f408365d5224a6f809c4c"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d0d51490cf719587b5b39db634525dcd7481de928c92f25184c449be57ed94a"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prq"
  desc "One-call PR state synthesis for AI coding agents — why is this PR blocked?"
  homepage "https://github.com/akira-toriyama/prq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prq"]
    end
  end

  # No zap stanza required

end
