# This file was generated by GoReleaser. DO NOT EDIT.
cask "prq" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "adbe144c7c5ed3fb4ffaca3d0bb68408dbcaad7d5a40081f369d49142ef7bcbd"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed1663cb7d73b86c734b64127a5bbe10b78283ad87b3e3c39d7a3e04418584e8"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6f23a6313adace58198c53bb9010128b449bb0f27e7e8136fba1a6ec3a9c42d"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d20271ee234dc48ebf58af73e38357b82f0b2018c87889d31602f8d0b5a4fde5"
      url "https://github.com/akira-toriyama/prq/releases/download/v#{version}/prq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prq"
  desc "One-call PR state synthesis for AI coding agents — why is this PR blocked?"
  homepage "https://github.com/akira-toriyama/prq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prq"]
    end
  end

  # No zap stanza required

end
