# This file was generated by GoReleaser. DO NOT EDIT.
cask "rundiff" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b9b47e737eba11fdff7a5b280cc5852677793382a87175a8533adee3e629365a"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "724524ec9701cd2fa2c60a0a534f1a067d2cffdbcd273fa3a9132f44e97edcc2"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13d4caa26a2b8456a60f23c0f67fa8f900e6155f8145c1a3e17d40aec9c036bd"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "129c61965d095d4b680ac3b39a698ba9c2bc1b85f01a2e555b4bea886a640708"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rundiff"
  desc "Diff a command's output against its previous run — fixed/new/unchanged for AI coding agents"
  homepage "https://github.com/akira-toriyama/rundiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rundiff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rundiff"]
    end
  end

  # No zap stanza required

end
