# This file was generated by GoReleaser. DO NOT EDIT.
cask "rundiff" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "4a6c8d80a9f85af18c14f2d60d42c1659ad731971f7bfbb200366b188b34263e"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a901d6cb65f9369fe8d23032dc0dec79434facf13a4ac8fb3085f46fce52b49c"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b6c16118ba64d5517d7d95fd2f8296406c6d6ef623592e90e3ba1674a7bc2dc"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "310be19fd10a6a07741fc73cb6d9d2d205c5637b53320331183e68264712146f"
      url "https://github.com/akira-toriyama/rundiff/releases/download/v#{version}/rundiff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rundiff"
  desc "Diff a command's output against its previous run — fixed/new/unchanged for AI coding agents"
  homepage "https://github.com/akira-toriyama/rundiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rundiff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rundiff"]
    end
  end

  # No zap stanza required

end
