class Perch < Formula
  desc "Keyboard-driven UI navigator for macOS — label everything, type to click"
  homepage "https://github.com/akira-toriyama/perch"
  # `url` / `sha256` are bumped automatically by the perch repo's
  # `.github/workflows/update-tap.yml` on every Published release.
  # Placeholder values here are good for the first run; the first
  # bump rewrites them to the real v1.x.y tag + tarball sha256.
  url "https://github.com/akira-toriyama/perch/archive/refs/tags/v4.0.0.tar.gz"
  sha256 "27341d6fddd54691372d6f710482fe03816fdcff443729df93395260c9002250"
  license "MIT"
  head "https://github.com/akira-toriyama/perch.git", branch: "main"

  # swift-tools-version 6.0 requires a Swift 6 toolchain. Builds with
  # the Xcode CLT swift just as well as a full Xcode.app — no full
  # IDE required at install time. macOS 13 (Ventura) is the floor.
  depends_on macos: :ventura

  def install
    # No external SwiftPM deps; --disable-sandbox lets swiftpm write
    # its cache under brew's restricted home.
    system "swift", "build", "--disable-sandbox", "-c", "release"

    app = prefix/"Perch.app"
    (app/"Contents/MacOS").mkpath
    cp "Info.plist", app/"Contents/Info.plist"
    cp ".build/release/perch", app/"Contents/MacOS/perch"

    # Ship the icon under Resources/ if the repo carries a committed
    # .icns. Generated by scripts/make-icon.sh; the Info.plist points
    # `CFBundleIconFile = Perch` at it.
    icns = "assets/Perch.icns"
    if File.exist?(icns)
      (app/"Contents/Resources").mkpath
      cp icns, app/"Contents/Resources/Perch.icns"
    end

    # Ship the signing helper under share/ so users can recover the
    # persistent-TCC path later via `brew reinstall`, without needing
    # to clone the source repo.
    pkgshare.install "setup-signing-cert.sh"
    chmod 0755, pkgshare/"setup-signing-cert.sh"

    # Hybrid signing (best-effort cert, loud fallback):
    # 1. Try to set up / reuse a stable per-user self-signed identity in
    #    the login keychain. When this works, the code-signing leaf hash
    #    stays constant across reinstalls, so TCC grants (Accessibility)
    #    persist across `brew upgrade`.
    # 2. If the script fails — locked login keychain, brew sandbox
    #    quirks, missing openssl, etc. — fall back to ad-hoc signing
    #    (always works) and emit a LOUD warning with a copy-pasteable
    #    recovery path. Without the warning the fallback is silent and
    #    users only notice when macOS re-prompts on every upgrade.
    #    Same pattern stroke / facet use.
    sign_id = "-"
    if quiet_system "./setup-signing-cert.sh"
      id_file = ".signing-id"
      sign_id = File.read(id_file).strip if File.exist?(id_file)
    end
    system "codesign", "--force", "--sign", sign_id, app

    if sign_id == "-"
      opoo <<~EOS
        Could not set up a stable self-signed identity in the login keychain —
        signed Perch.app ad-hoc. The app works fine, but every
        `brew upgrade perch` produces a new code hash, so macOS will
        re-prompt for Accessibility on every upgrade.

        To make grants persist across upgrades, run once after install:
          #{opt_pkgshare}/setup-signing-cert.sh
          brew reinstall perch

        Verify:
          codesign -dvv #{opt_prefix}/Perch.app
          # expect: Authority="perch Local Signing"
      EOS
    else
      ohai "Signed Perch.app with stable self-signed identity " \
           "(\"#{sign_id}\") — TCC grants persist across upgrades."
    end

    # Same binary doubles as the thin CLI client (--reload / --quit /
    # --status / --doctor / --validate / --help).
    bin.install_symlink app/"Contents/MacOS/perch" => "perch"
  end

  def caveats
    <<~EOS
      perch is a keyboard-driven UI navigator (LSUIElement, no Dock icon).
      Press the global hotkey (default shift+space), every clickable
      element in the frontmost native app gets a short letter label —
      type the label to click. Native macOS apps only; Chrome / Electron
      are out of scope for the MVP.

      First-run setup:
        1) Drop the config template:
             curl --create-dirs -o ~/.config/perch/config.toml \\
               https://raw.githubusercontent.com/akira-toriyama/perch/main/config.toml
        2) Launch the daemon once so macOS shows the AX prompt:
             open #{opt_prefix}/Perch.app
        3) Grant Accessibility to "perch" (System Settings → Privacy &
           Security → Accessibility), then relaunch with `perch`.

      CLI (no daemon needed for these):
        perch --validate     parse config.toml
        perch --doctor       health check (AX / config / daemon / hotkey)
        perch --help         all flags

      Client commands (talk to the running daemon over DNC):
        perch --reload       re-read config.toml live
        perch --status       active hotkey + last activation
        perch --quit         terminate the running daemon

      Auto-start on login (optional):
        Add #{opt_prefix}/Perch.app to System Settings → General → Login Items.

      Persistent Accessibility grants across `brew upgrade` need a stable
      code-signing identity. The install creates one automatically when it
      can; if the install printed a "fell back to ad-hoc" warning (or
      `codesign -dvv #{opt_prefix}/Perch.app` shows no Authority line),
      run once:
        #{opt_pkgshare}/setup-signing-cert.sh
        brew reinstall perch
    EOS
  end

  test do
    assert_path_exists prefix/"Perch.app/Contents/MacOS/perch"
    # --validate touches no AX / hotkey — safe in the test sandbox.
    system bin/"perch", "--validate"
  end
end
